services:
  backend:
    build: ./backend
    container_name: gizbar-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gizbar-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html # Mount local dist to container (optional but good for quick updates)
    depends_on:
      - backend
