services:
  backend:
    build: ./backend
    container_name: gizbar-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: gizbar-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
